default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: trac_development

test:
  <<: *default
  database: trac_test

production:
  <<: *default
  database: trac_production
  username: trac
  password: <%= ENV['TRAC_DATABASE_PASSWORD'] %>
